import type { Order } from "./types"

export const mockOrders: Order[] = [
  {
    id: "ORD-1703123456789",
    userId: "1",
    items: [
      {
        product: {
          id: "1",
          name: "Premium Wireless Headphones",
          description: "High-quality wireless headphones with noise cancellation and premium sound quality.",
          price: 299.99,
          originalPrice: 399.99,
          image: "/premium-wireless-headphones-black.jpg",
          category: "Electronics",
          rating: 4.8,
          reviewCount: 1247,
          inStock: true,
          features: ["Active Noise Cancellation", "30-hour Battery Life", "Premium Sound Quality", "Comfortable Fit"],
        },
        quantity: 1,
      },
      {
        product: {
          id: "3",
          name: "Organic Cotton T-Shirt",
          description: "Comfortable and sustainable organic cotton t-shirt.",
          price: 29.99,
          originalPrice: 39.99,
          image: "/organic-cotton-t-shirt-white.jpg",
          category: "Clothing",
          rating: 4.4,
          reviewCount: 324,
          inStock: true,
          features: ["100% Organic Cotton", "Sustainable Production", "Comfortable Fit", "Machine Washable"],
        },
        quantity: 2,
      },
    ],
    total: 359.97,
    status: "delivered",
    createdAt: new Date("2024-01-15"),
    shippingAddress: {
      street: "123 Main St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      country: "United States",
    },
  },
  {
    id: "ORD-1703023456789",
    userId: "1",
    items: [
      {
        product: {
          id: "2",
          name: "Smart Fitness Watch",
          description: "Advanced fitness tracking with heart rate monitoring, GPS, and smartphone integration.",
          price: 249.99,
          image: "/smart-fitness-watch-silver.jpg",
          category: "Electronics",
          rating: 4.6,
          reviewCount: 892,
          inStock: true,
          features: ["Heart Rate Monitor", "GPS Tracking", "Water Resistant", "Smart Notifications"],
        },
        quantity: 1,
      },
    ],
    total: 249.99,
    status: "shipped",
    createdAt: new Date("2024-01-20"),
    shippingAddress: {
      street: "123 Main St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      country: "United States",
    },
  },
  {
    id: "ORD-1702923456789",
    userId: "1",
    items: [
      {
        product: {
          id: "5",
          name: "Minimalist Desk Lamp",
          description: "Modern LED desk lamp with adjustable brightness and color temperature.",
          price: 79.99,
          image: "/minimalist-led-desk-lamp-white.jpg",
          category: "Home & Office",
          rating: 4.5,
          reviewCount: 445,
          inStock: true,
          features: ["LED Technology", "Adjustable Brightness", "Color Temperature Control", "USB Charging Port"],
        },
        quantity: 1,
      },
      {
        product: {
          id: "6",
          name: "Premium Coffee Beans",
          description: "Single-origin coffee beans roasted to perfection.",
          price: 24.99,
          image: "/premium-coffee-beans-bag.jpg",
          category: "Food & Beverage",
          rating: 4.7,
          reviewCount: 678,
          inStock: true,
          features: ["Single Origin", "Freshly Roasted", "Fair Trade", "Rich Flavor Profile"],
        },
        quantity: 3,
      },
    ],
    total: 154.96,
    status: "processing",
    createdAt: new Date("2024-01-25"),
    shippingAddress: {
      street: "123 Main St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      country: "United States",
    },
  },
]
