import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description:
      "High-quality wireless headphones with noise cancellation and premium sound quality. Perfect for music lovers and professionals.",
    price: 24899,
    originalPrice: 33199,
    image: "/premium-wireless-headphones-black.jpg",
    category: "Electronics",
    rating: 4.8,
    reviewCount: 1247,
    inStock: true,
    features: ["Active Noise Cancellation", "30-hour Battery Life", "Premium Sound Quality", "Comfortable Fit"],
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description:
      "Advanced fitness tracking with heart rate monitoring, GPS, and smartphone integration. Track your health and stay connected.",
    price: 20749,
    image: "/smart-fitness-watch-silver.jpg",
    category: "Electronics",
    rating: 4.6,
    reviewCount: 892,
    inStock: true,
    features: ["Heart Rate Monitor", "GPS Tracking", "Water Resistant", "Smart Notifications"],
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable organic cotton t-shirt. Soft, breathable, and perfect for everyday wear.",
    price: 2499,
    originalPrice: 3319,
    image: "/organic-cotton-t-shirt-white.jpg",
    category: "Clothing",
    rating: 4.4,
    reviewCount: 324,
    inStock: true,
    features: ["100% Organic Cotton", "Sustainable Production", "Comfortable Fit", "Machine Washable"],
  },
  {
    id: "4",
    name: "Professional Camera Lens",
    description: "High-performance camera lens for professional photography. Sharp images with beautiful bokeh effect.",
    price: 74699,
    image: "/professional-camera-lens-black.jpg",
    category: "Electronics",
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    features: ["Professional Grade", "Sharp Images", "Beautiful Bokeh", "Durable Build"],
  },
  {
    id: "5",
    name: "Minimalist LED Desk Lamp",
    description: "Modern LED desk lamp with adjustable brightness and color temperature. Perfect for work and study.",
    price: 8299,
    originalPrice: 12449,
    image: "/minimalist-led-desk-lamp-white.jpg",
    category: "Home & Office",
    rating: 4.5,
    reviewCount: 423,
    inStock: true,
    features: ["Adjustable Brightness", "Color Temperature Control", "Modern Design", "Energy Efficient"],
  },
  {
    id: "6",
    name: "Premium Coffee Beans",
    description:
      "Single-origin coffee beans roasted to perfection. Rich flavor profile with notes of chocolate and caramel.",
    price: 2074,
    image: "/premium-coffee-beans-bag.jpg",
    category: "Food & Beverage",
    rating: 4.7,
    reviewCount: 678,
    inStock: true,
    features: ["Single Origin", "Freshly Roasted", "Fair Trade", "Rich Flavor Profile"],
  },
  // Electronics
  {
    id: "7",
    name: "Gaming Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard with tactile switches. Perfect for gaming and productivity.",
    price: 8299,
    originalPrice: 12449,
    image: "/gaming-mechanical-keyboard-rgb.jpg",
    category: "Electronics",
    rating: 4.7,
    reviewCount: 523,
    inStock: true,
    features: ["Mechanical Switches", "RGB Backlighting", "Anti-Ghosting", "Durable Build"],
  },
  {
    id: "8",
    name: "Wireless Gaming Mouse",
    description: "High-precision wireless gaming mouse with customizable DPI and programmable buttons.",
    price: 4979,
    image: "/wireless-gaming-mouse-black.jpg",
    category: "Electronics",
    rating: 4.6,
    reviewCount: 789,
    inStock: true,
    features: ["High DPI Sensor", "Wireless Connectivity", "Programmable Buttons", "Long Battery Life"],
  },
  {
    id: "9",
    name: "4K Webcam",
    description: "Ultra HD webcam with auto-focus and noise-canceling microphone for professional video calls.",
    price: 12449,
    image: "/4k-webcam-professional.jpg",
    category: "Electronics",
    rating: 4.5,
    reviewCount: 234,
    inStock: true,
    features: ["4K Resolution", "Auto Focus", "Noise Canceling Mic", "Plug & Play"],
  },
  {
    id: "10",
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with 360-degree sound and waterproof design.",
    price: 6639,
    originalPrice: 9959,
    image: "/bluetooth-speaker-portable-waterproof.jpg",
    category: "Electronics",
    rating: 4.4,
    reviewCount: 1156,
    inStock: true,
    features: ["360° Sound", "Waterproof", "20-hour Battery", "Voice Assistant"],
  },
  {
    id: "11",
    name: "Smartphone Stand",
    description: "Adjustable aluminum smartphone stand for desk use. Compatible with all phone sizes.",
    price: 1659,
    image: "/aluminum-smartphone-stand-adjustable.jpg",
    category: "Electronics",
    rating: 4.3,
    reviewCount: 445,
    inStock: true,
    features: ["Adjustable Angle", "Aluminum Build", "Universal Compatibility", "Non-slip Base"],
  },
  {
    id: "12",
    name: "USB-C Hub",
    description: "7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader, and power delivery.",
    price: 4149,
    image: "/usb-c-hub-7-in-1-hdmi.jpg",
    category: "Electronics",
    rating: 4.6,
    reviewCount: 678,
    inStock: true,
    features: ["7-in-1 Design", "4K HDMI Output", "Fast Data Transfer", "Power Delivery"],
  },
  {
    id: "13",
    name: "Wireless Earbuds",
    description: "True wireless earbuds with active noise cancellation and premium sound quality.",
    price: 16599,
    originalPrice: 24899,
    image: "/wireless-earbuds-white-case.jpg",
    category: "Electronics",
    rating: 4.7,
    reviewCount: 2134,
    inStock: true,
    features: ["Active Noise Cancellation", "Wireless Charging", "IPX4 Water Resistant", "Touch Controls"],
  },
  {
    id: "14",
    name: "Power Bank 20000mAh",
    description: "High-capacity power bank with fast charging and multiple USB ports.",
    price: 3319,
    image: "/power-bank-20000mah-black.jpg",
    category: "Electronics",
    rating: 4.5,
    reviewCount: 892,
    inStock: true,
    features: ["20000mAh Capacity", "Fast Charging", "Multiple Ports", "LED Display"],
  },
  {
    id: "15",
    name: "Tablet Stand",
    description: "Foldable tablet stand with adjustable height and angle. Perfect for video calls and reading.",
    price: 2489,
    image: "/tablet-stand-foldable-adjustable.jpg",
    category: "Electronics",
    rating: 4.4,
    reviewCount: 356,
    inStock: true,
    features: ["Foldable Design", "Adjustable Height", "Universal Compatibility", "Stable Base"],
  },
  // Clothing
  {
    id: "16",
    name: "Cotton Polo Shirt",
    description: "Classic cotton polo shirt in navy blue. Comfortable fit for casual and semi-formal occasions.",
    price: 1999,
    originalPrice: 2999,
    image: "/cotton-polo-shirt-navy-blue.jpg",
    category: "Clothing",
    rating: 4.3,
    reviewCount: 567,
    inStock: true,
    features: ["100% Cotton", "Classic Fit", "Breathable Fabric", "Machine Washable"],
  },
  {
    id: "17",
    name: "Denim Jeans",
    description: "Premium denim jeans with slim fit and comfortable stretch. Perfect for everyday wear.",
    price: 3999,
    image: "/denim-jeans-slim-fit-blue.jpg",
    category: "Clothing",
    rating: 4.5,
    reviewCount: 789,
    inStock: true,
    features: ["Premium Denim", "Slim Fit", "Stretch Comfort", "Fade Resistant"],
  },
  {
    id: "18",
    name: "Formal Shirt",
    description: "Crisp white formal shirt made from premium cotton. Perfect for office and formal events.",
    price: 2499,
    image: "/white-formal-shirt-cotton.jpg",
    category: "Clothing",
    rating: 4.6,
    reviewCount: 445,
    inStock: true,
    features: ["Premium Cotton", "Wrinkle Resistant", "Regular Fit", "Easy Care"],
  },
  {
    id: "19",
    name: "Casual Sneakers",
    description: "Comfortable casual sneakers with cushioned sole and breathable upper.",
    price: 4999,
    originalPrice: 6999,
    image: "/casual-sneakers-white-comfortable.jpg",
    category: "Clothing",
    rating: 4.4,
    reviewCount: 1234,
    inStock: true,
    features: ["Cushioned Sole", "Breathable Upper", "Lightweight", "Versatile Style"],
  },
  {
    id: "20",
    name: "Hoodie",
    description: "Cozy cotton hoodie with kangaroo pocket and adjustable drawstring hood.",
    price: 3499,
    image: "/cotton-hoodie-gray-kangaroo-pocket.jpg",
    category: "Clothing",
    rating: 4.5,
    reviewCount: 678,
    inStock: true,
    features: ["Cotton Blend", "Kangaroo Pocket", "Adjustable Hood", "Comfortable Fit"],
  },
  {
    id: "21",
    name: "Summer Dress",
    description: "Flowy summer dress in floral print. Light and comfortable for warm weather.",
    price: 2999,
    image: "/summer-dress-floral-print-flowing.jpg",
    category: "Clothing",
    rating: 4.3,
    reviewCount: 234,
    inStock: true,
    features: ["Floral Print", "Lightweight Fabric", "Comfortable Fit", "Summer Ready"],
  },
  {
    id: "22",
    name: "Leather Belt",
    description: "Genuine leather belt with classic buckle. Perfect accessory for formal and casual wear.",
    price: 1999,
    image: "/leather-belt-brown-classic-buckle.jpg",
    category: "Clothing",
    rating: 4.6,
    reviewCount: 456,
    inStock: true,
    features: ["Genuine Leather", "Classic Buckle", "Adjustable Size", "Durable Construction"],
  },
  {
    id: "23",
    name: "Sports Shorts",
    description: "Athletic shorts with moisture-wicking fabric and comfortable fit for workouts.",
    price: 1499,
    image: "/sports-shorts-athletic-black.jpg",
    category: "Clothing",
    rating: 4.4,
    reviewCount: 567,
    inStock: true,
    features: ["Moisture Wicking", "Elastic Waistband", "Lightweight", "Quick Dry"],
  },
  {
    id: "24",
    name: "Winter Jacket",
    description: "Warm winter jacket with insulation and water-resistant outer shell.",
    price: 7999,
    originalPrice: 11999,
    image: "/winter-jacket-insulated-navy.jpg",
    category: "Clothing",
    rating: 4.7,
    reviewCount: 345,
    inStock: true,
    features: ["Insulated", "Water Resistant", "Multiple Pockets", "Adjustable Hood"],
  },
  {
    id: "25",
    name: "Running Shoes",
    description: "Professional running shoes with advanced cushioning and breathable mesh upper.",
    price: 8999,
    image: "/running-shoes-professional-black.jpg",
    category: "Clothing",
    rating: 4.8,
    reviewCount: 1567,
    inStock: true,
    features: ["Advanced Cushioning", "Breathable Mesh", "Lightweight", "Durable Sole"],
  },
  // Home & Office
  {
    id: "26",
    name: "Office Chair",
    description: "Ergonomic office chair with lumbar support and adjustable height. Perfect for long work hours.",
    price: 12999,
    originalPrice: 19999,
    image: "/office-chair-ergonomic-black.jpg",
    category: "Home & Office",
    rating: 4.6,
    reviewCount: 789,
    inStock: true,
    features: ["Ergonomic Design", "Lumbar Support", "Adjustable Height", "Breathable Mesh"],
  },
  {
    id: "27",
    name: "Standing Desk",
    description: "Height-adjustable standing desk with electric motor and memory presets.",
    price: 24999,
    image: "/standing-desk-adjustable-white.jpg",
    category: "Home & Office",
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    features: ["Electric Height Adjustment", "Memory Presets", "Sturdy Construction", "Cable Management"],
  },
  {
    id: "28",
    name: "Bookshelf",
    description: "5-tier wooden bookshelf with modern design. Perfect for books, decor, and storage.",
    price: 8999,
    image: "/bookshelf-5-tier-wooden.jpg",
    category: "Home & Office",
    rating: 4.4,
    reviewCount: 456,
    inStock: true,
    features: ["5-Tier Design", "Wooden Construction", "Modern Style", "Easy Assembly"],
  },
  {
    id: "29",
    name: "Table Lamp",
    description: "Modern table lamp with touch control and dimmable LED light.",
    price: 3999,
    image: "/table-lamp-modern-touch-control.jpg",
    category: "Home & Office",
    rating: 4.5,
    reviewCount: 345,
    inStock: true,
    features: ["Touch Control", "Dimmable LED", "Modern Design", "Energy Efficient"],
  },
  {
    id: "30",
    name: "Storage Organizer",
    description: "Multi-compartment storage organizer for office supplies and small items.",
    price: 1999,
    image: "/storage-organizer-multi-compartment.jpg",
    category: "Home & Office",
    rating: 4.3,
    reviewCount: 567,
    inStock: true,
    features: ["Multiple Compartments", "Durable Plastic", "Stackable Design", "Clear Visibility"],
  },
  {
    id: "31",
    name: "Wall Clock",
    description: "Silent wall clock with modern design and large numbers for easy reading.",
    price: 2499,
    image: "/wall-clock-silent-modern.jpg",
    category: "Home & Office",
    rating: 4.4,
    reviewCount: 234,
    inStock: true,
    features: ["Silent Movement", "Modern Design", "Large Numbers", "Easy Installation"],
  },
  {
    id: "32",
    name: "Desk Organizer",
    description: "Bamboo desk organizer with multiple compartments for pens, papers, and accessories.",
    price: 2999,
    image: "/desk-organizer-bamboo-natural.jpg",
    category: "Home & Office",
    rating: 4.5,
    reviewCount: 678,
    inStock: true,
    features: ["Bamboo Construction", "Multiple Compartments", "Eco-Friendly", "Natural Finish"],
  },
  {
    id: "33",
    name: "Floor Lamp",
    description: "Adjustable floor lamp with reading light and ambient lighting modes.",
    price: 7999,
    image: "/floor-lamp-adjustable-reading.jpg",
    category: "Home & Office",
    rating: 4.6,
    reviewCount: 345,
    inStock: true,
    features: ["Adjustable Height", "Reading Light", "Ambient Mode", "Touch Controls"],
  },
  {
    id: "34",
    name: "Monitor Stand",
    description: "Wooden monitor stand with storage drawer for keyboard and office supplies.",
    price: 3499,
    image: "/monitor-stand-wooden-drawer.jpg",
    category: "Home & Office",
    rating: 4.4,
    reviewCount: 456,
    inStock: true,
    features: ["Wooden Construction", "Storage Drawer", "Ergonomic Height", "Cable Management"],
  },
  {
    id: "35",
    name: "Whiteboard",
    description: "Magnetic whiteboard with aluminum frame and marker tray.",
    price: 4999,
    image: "/whiteboard-magnetic-aluminum-frame.jpg",
    category: "Home & Office",
    rating: 4.5,
    reviewCount: 234,
    inStock: true,
    features: ["Magnetic Surface", "Aluminum Frame", "Marker Tray", "Easy Installation"],
  },
  // Food & Beverage
  {
    id: "36",
    name: "Green Tea",
    description: "Premium green tea leaves with antioxidants and natural flavor.",
    price: 899,
    image: "/green-tea-premium-leaves.jpg",
    category: "Food & Beverage",
    rating: 4.6,
    reviewCount: 789,
    inStock: true,
    features: ["Premium Quality", "Rich in Antioxidants", "Natural Flavor", "Loose Leaf"],
  },
  {
    id: "37",
    name: "Honey",
    description: "Pure organic honey harvested from wildflowers. Natural sweetener with health benefits.",
    price: 1499,
    image: "/honey-organic-wildflower.jpg",
    category: "Food & Beverage",
    rating: 4.7,
    reviewCount: 456,
    inStock: true,
    features: ["100% Pure", "Organic", "Wildflower Source", "Natural Sweetener"],
  },
  {
    id: "38",
    name: "Dark Chocolate",
    description: "Premium dark chocolate with 70% cocoa content. Rich flavor and health benefits.",
    price: 799,
    image: "/dark-chocolate-70-percent-cocoa.jpg",
    category: "Food & Beverage",
    rating: 4.5,
    reviewCount: 567,
    inStock: true,
    features: ["70% Cocoa", "Premium Quality", "Rich Flavor", "Antioxidant Rich"],
  },
  {
    id: "39",
    name: "Olive Oil",
    description: "Extra virgin olive oil cold-pressed from Mediterranean olives.",
    price: 1999,
    image: "/olive-oil-extra-virgin-mediterranean.jpg",
    category: "Food & Beverage",
    rating: 4.8,
    reviewCount: 345,
    inStock: true,
    features: ["Extra Virgin", "Cold Pressed", "Mediterranean Origin", "Premium Quality"],
  },
  {
    id: "40",
    name: "Protein Powder",
    description: "Whey protein powder for muscle building and recovery. Vanilla flavor.",
    price: 3999,
    image: "/protein-powder-whey-vanilla.jpg",
    category: "Food & Beverage",
    rating: 4.4,
    reviewCount: 1234,
    inStock: true,
    features: ["Whey Protein", "Muscle Building", "Vanilla Flavor", "Easy Mixing"],
  },
  {
    id: "41",
    name: "Almonds",
    description: "Raw almonds packed with nutrients and healthy fats. Perfect for snacking.",
    price: 1299,
    image: "/almonds-raw-natural.jpg",
    category: "Food & Beverage",
    rating: 4.6,
    reviewCount: 678,
    inStock: true,
    features: ["Raw Almonds", "Nutrient Rich", "Healthy Fats", "Natural Snack"],
  },
  {
    id: "42",
    name: "Herbal Tea Mix",
    description: "Blend of chamomile, lavender, and mint for relaxation and better sleep.",
    price: 1199,
    image: "/herbal-tea-mix-chamomile-lavender.jpg",
    category: "Food & Beverage",
    rating: 4.5,
    reviewCount: 234,
    inStock: true,
    features: ["Herbal Blend", "Relaxation", "Sleep Aid", "Natural Ingredients"],
  },
  {
    id: "43",
    name: "Coconut Oil",
    description: "Virgin coconut oil for cooking and skincare. Cold-pressed and unrefined.",
    price: 1699,
    image: "/coconut-oil-virgin-cold-pressed.jpg",
    category: "Food & Beverage",
    rating: 4.7,
    reviewCount: 456,
    inStock: true,
    features: ["Virgin Quality", "Cold Pressed", "Multi-Purpose", "Unrefined"],
  },
  {
    id: "44",
    name: "Quinoa",
    description: "Organic quinoa grains rich in protein and fiber. Perfect for healthy meals.",
    price: 999,
    image: "/quinoa-organic-grains.jpg",
    category: "Food & Beverage",
    rating: 4.4,
    reviewCount: 345,
    inStock: true,
    features: ["Organic", "High Protein", "Rich in Fiber", "Gluten Free"],
  },
  {
    id: "45",
    name: "Spice Set",
    description: "Collection of 12 essential spices for Indian cooking in airtight containers.",
    price: 2499,
    image: "/spice-set-indian-cooking-12-pieces.jpg",
    category: "Food & Beverage",
    rating: 4.6,
    reviewCount: 567,
    inStock: true,
    features: ["12 Essential Spices", "Airtight Containers", "Indian Cooking", "Fresh Quality"],
  },
  // Books & Education
  {
    id: "46",
    name: "Programming Book",
    description: "Complete guide to JavaScript programming with practical examples and projects.",
    price: 1999,
    image: "/programming-book-javascript-guide.jpg",
    category: "Books",
    rating: 4.7,
    reviewCount: 456,
    inStock: true,
    features: ["Comprehensive Guide", "Practical Examples", "Project-Based", "Latest Standards"],
  },
  {
    id: "47",
    name: "Notebook Set",
    description: "Set of 3 premium notebooks with dotted pages for bullet journaling and note-taking.",
    price: 1499,
    image: "/notebook-set-dotted-pages-3-pieces.jpg",
    category: "Books",
    rating: 4.5,
    reviewCount: 789,
    inStock: true,
    features: ["Premium Paper", "Dotted Pages", "Bullet Journal", "Set of 3"],
  },
  {
    id: "48",
    name: "Art Supplies Kit",
    description: "Complete art supplies kit with pencils, erasers, and sketchbook for beginners.",
    price: 2999,
    image: "/art-supplies-kit-complete-beginner.jpg",
    category: "Books",
    rating: 4.4,
    reviewCount: 234,
    inStock: true,
    features: ["Complete Kit", "Beginner Friendly", "Quality Materials", "Includes Sketchbook"],
  },
  {
    id: "49",
    name: "Dictionary",
    description: "Comprehensive English dictionary with over 50,000 words and definitions.",
    price: 1799,
    image: "/dictionary-english-comprehensive.jpg",
    category: "Books",
    rating: 4.6,
    reviewCount: 345,
    inStock: true,
    features: ["50,000+ Words", "Comprehensive", "Clear Definitions", "Reference Guide"],
  },
  {
    id: "50",
    name: "Cookbook",
    description: "Indian cuisine cookbook with 100 traditional recipes and cooking techniques.",
    price: 2299,
    image: "/cookbook-indian-cuisine-traditional.jpg",
    category: "Books",
    rating: 4.8,
    reviewCount: 567,
    inStock: true,
    features: ["100 Recipes", "Traditional Cuisine", "Step-by-Step", "Cooking Techniques"],
  },
  // Sports & Fitness
  {
    id: "51",
    name: "Yoga Mat",
    description: "Non-slip yoga mat with extra cushioning for comfortable practice.",
    price: 2499,
    image: "/yoga-mat-non-slip-purple.jpg",
    category: "Sports",
    rating: 4.5,
    reviewCount: 1234,
    inStock: true,
    features: ["Non-Slip Surface", "Extra Cushioning", "Eco-Friendly", "Portable"],
  },
  {
    id: "52",
    name: "Dumbbells Set",
    description: "Adjustable dumbbells set with weight plates for home workouts.",
    price: 7999,
    image: "/dumbbells-set-adjustable-home.jpg",
    category: "Sports",
    rating: 4.6,
    reviewCount: 456,
    inStock: true,
    features: ["Adjustable Weight", "Home Workout", "Durable Construction", "Space Saving"],
  },
  {
    id: "53",
    name: "Resistance Bands",
    description: "Set of 5 resistance bands with different resistance levels for strength training.",
    price: 1999,
    image: "/resistance-bands-set-5-levels.jpg",
    category: "Sports",
    rating: 4.4,
    reviewCount: 789,
    inStock: true,
    features: ["5 Resistance Levels", "Portable", "Full Body Workout", "Durable Material"],
  },
  {
    id: "54",
    name: "Water Bottle",
    description: "Insulated stainless steel water bottle that keeps drinks cold for 24 hours.",
    price: 1499,
    image: "/water-bottle-insulated-stainless-steel.jpg",
    category: "Sports",
    rating: 4.7,
    reviewCount: 1567,
    inStock: true,
    features: ["24-Hour Cold", "Stainless Steel", "Leak Proof", "BPA Free"],
  },
  {
    id: "55",
    name: "Exercise Ball",
    description: "Anti-burst exercise ball for core strengthening and balance training.",
    price: 1999,
    image: "/exercise-ball-anti-burst-blue.jpg",
    category: "Sports",
    rating: 4.3,
    reviewCount: 345,
    inStock: true,
    features: ["Anti-Burst", "Core Strengthening", "Balance Training", "Multiple Sizes"],
  },
  // Beauty & Personal Care
  {
    id: "56",
    name: "Face Moisturizer",
    description: "Hydrating face moisturizer with SPF 30 protection for daily use.",
    price: 1999,
    image: "/face-moisturizer-spf30-hydrating.jpg",
    category: "Beauty",
    rating: 4.5,
    reviewCount: 678,
    inStock: true,
    features: ["SPF 30 Protection", "Hydrating Formula", "Daily Use", "All Skin Types"],
  },
  {
    id: "57",
    name: "Shampoo",
    description: "Sulfate-free shampoo for all hair types with natural ingredients.",
    price: 1299,
    image: "/shampoo-sulfate-free-natural.jpg",
    category: "Beauty",
    rating: 4.4,
    reviewCount: 456,
    inStock: true,
    features: ["Sulfate Free", "Natural Ingredients", "All Hair Types", "Gentle Formula"],
  },
  {
    id: "58",
    name: "Body Lotion",
    description: "Nourishing body lotion with shea butter and vitamin E for soft skin.",
    price: 1699,
    image: "/body-lotion-shea-butter-vitamin-e.jpg",
    category: "Beauty",
    rating: 4.6,
    reviewCount: 789,
    inStock: true,
    features: ["Shea Butter", "Vitamin E", "Nourishing", "Fast Absorbing"],
  },
  {
    id: "59",
    name: "Lip Balm Set",
    description: "Set of 3 lip balms with different flavors for moisturized lips.",
    price: 899,
    image: "/lip-balm-set-3-flavors.jpg",
    category: "Beauty",
    rating: 4.3,
    reviewCount: 234,
    inStock: true,
    features: ["Set of 3", "Different Flavors", "Moisturizing", "Natural Ingredients"],
  },
  {
    id: "60",
    name: "Face Mask",
    description: "Hydrating sheet mask with hyaluronic acid for instant moisture boost.",
    price: 599,
    image: "/face-mask-hyaluronic-acid-sheet.jpg",
    category: "Beauty",
    rating: 4.4,
    reviewCount: 567,
    inStock: true,
    features: ["Hyaluronic Acid", "Instant Hydration", "Sheet Mask", "Single Use"],
  },
  // Toys & Games
  {
    id: "61",
    name: "Board Game",
    description: "Strategy board game for 2-4 players with engaging gameplay and beautiful artwork.",
    price: 2999,
    image: "/board-game-strategy-2-4-players.jpg",
    category: "Toys",
    rating: 4.7,
    reviewCount: 345,
    inStock: true,
    features: ["2-4 Players", "Strategy Game", "Beautiful Artwork", "Family Friendly"],
  },
  {
    id: "62",
    name: "Puzzle 1000 Pieces",
    description: "Challenging 1000-piece jigsaw puzzle with stunning landscape artwork.",
    price: 1499,
    image: "/puzzle-1000-pieces-landscape.jpg",
    category: "Toys",
    rating: 4.5,
    reviewCount: 456,
    inStock: true,
    features: ["1000 Pieces", "Landscape Art", "Challenging", "High Quality"],
  },
  {
    id: "63",
    name: "Building Blocks",
    description: "Creative building blocks set with 500 pieces for endless construction possibilities.",
    price: 3999,
    image: "/building-blocks-creative-500-pieces.jpg",
    category: "Toys",
    rating: 4.6,
    reviewCount: 789,
    inStock: true,
    features: ["500 Pieces", "Creative Building", "Educational", "Safe Materials"],
  },
  {
    id: "64",
    name: "Remote Control Car",
    description: "High-speed remote control car with rechargeable battery and LED lights.",
    price: 4999,
    image: "/remote-control-car-high-speed-led.jpg",
    category: "Toys",
    rating: 4.4,
    reviewCount: 234,
    inStock: true,
    features: ["High Speed", "Rechargeable Battery", "LED Lights", "Remote Control"],
  },
  {
    id: "65",
    name: "Action Figure",
    description: "Collectible action figure with multiple articulation points and accessories.",
    price: 1999,
    image: "/action-figure-collectible-articulated.jpg",
    category: "Toys",
    rating: 4.5,
    reviewCount: 567,
    inStock: true,
    features: ["Collectible", "Articulated", "Accessories Included", "High Detail"],
  },
  // Garden & Outdoor
  {
    id: "66",
    name: "Plant Pot Set",
    description: "Set of 3 ceramic plant pots with drainage holes for indoor plants.",
    price: 1999,
    image: "/plant-pot-set-ceramic-3-pieces.jpg",
    category: "Garden",
    rating: 4.4,
    reviewCount: 345,
    inStock: true,
    features: ["Set of 3", "Ceramic Material", "Drainage Holes", "Indoor Plants"],
  },
  {
    id: "67",
    name: "Garden Tools Set",
    description: "Essential garden tools set with trowel, pruner, and watering can.",
    price: 2999,
    image: "/garden-tools-set-essential-complete.jpg",
    category: "Garden",
    rating: 4.6,
    reviewCount: 456,
    inStock: true,
    features: ["Essential Tools", "Durable Construction", "Ergonomic Design", "Complete Set"],
  },
  {
    id: "68",
    name: "Solar Lights",
    description: "Set of 6 solar-powered garden lights with automatic on/off feature.",
    price: 3499,
    image: "/solar-lights-garden-6-pieces-automatic.jpg",
    category: "Garden",
    rating: 4.5,
    reviewCount: 678,
    inStock: true,
    features: ["Solar Powered", "Set of 6", "Automatic On/Off", "Weather Resistant"],
  },
  {
    id: "69",
    name: "Fertilizer",
    description: "Organic fertilizer for all plants with slow-release nutrients.",
    price: 899,
    image: "/fertilizer-organic-slow-release.jpg",
    category: "Garden",
    rating: 4.3,
    reviewCount: 234,
    inStock: true,
    features: ["Organic", "All Plants", "Slow Release", "Nutrient Rich"],
  },
  {
    id: "70",
    name: "Watering Hose",
    description: "Expandable garden hose that extends to 50 feet with spray nozzle.",
    price: 2499,
    image: "/watering-hose-expandable-50-feet.jpg",
    category: "Garden",
    rating: 4.4,
    reviewCount: 567,
    inStock: true,
    features: ["Expandable", "50 Feet Length", "Spray Nozzle", "Lightweight"],
  },
  // Automotive
  {
    id: "71",
    name: "Car Phone Mount",
    description: "Magnetic car phone mount with 360-degree rotation and strong grip.",
    price: 1499,
    image: "/car-phone-mount-magnetic-360.jpg",
    category: "Automotive",
    rating: 4.5,
    reviewCount: 789,
    inStock: true,
    features: ["Magnetic Mount", "360° Rotation", "Strong Grip", "Universal Fit"],
  },
  {
    id: "72",
    name: "Car Charger",
    description: "Dual USB car charger with fast charging capability for smartphones and tablets.",
    price: 999,
    image: "/car-charger-dual-usb-fast.jpg",
    category: "Automotive",
    rating: 4.4,
    reviewCount: 456,
    inStock: true,
    features: ["Dual USB", "Fast Charging", "Universal Compatibility", "Compact Design"],
  },
  {
    id: "73",
    name: "Car Air Freshener",
    description: "Long-lasting car air freshener with vanilla scent and clip-on design.",
    price: 299,
    image: "/car-air-freshener-vanilla-clip.jpg",
    category: "Automotive",
    rating: 4.2,
    reviewCount: 234,
    inStock: true,
    features: ["Vanilla Scent", "Long Lasting", "Clip-On Design", "Car Interior"],
  },
  {
    id: "74",
    name: "Tire Pressure Gauge",
    description: "Digital tire pressure gauge with LCD display and accurate readings.",
    price: 1999,
    image: "/tire-pressure-gauge-digital-lcd.jpg",
    category: "Automotive",
    rating: 4.6,
    reviewCount: 345,
    inStock: true,
    features: ["Digital Display", "Accurate Readings", "LCD Screen", "Easy to Use"],
  },
  {
    id: "75",
    name: "Car Cleaning Kit",
    description: "Complete car cleaning kit with microfiber cloths, spray, and detailing tools.",
    price: 2999,
    image: "/car-cleaning-kit-complete-microfiber.jpg",
    category: "Automotive",
    rating: 4.5,
    reviewCount: 567,
    inStock: true,
    features: ["Complete Kit", "Microfiber Cloths", "Cleaning Spray", "Detailing Tools"],
  },
  // Pet Supplies
  {
    id: "76",
    name: "Dog Food",
    description: "Premium dry dog food with chicken and rice for adult dogs.",
    price: 2499,
    image: "/dog-food-premium-chicken-rice.jpg",
    category: "Pets",
    rating: 4.7,
    reviewCount: 1234,
    inStock: true,
    features: ["Premium Quality", "Chicken & Rice", "Adult Dogs", "Nutritious"],
  },
  {
    id: "77",
    name: "Cat Litter",
    description: "Clumping cat litter with odor control and dust-free formula.",
    price: 1999,
    image: "/cat-litter-clumping-odor-control.jpg",
    category: "Pets",
    rating: 4.5,
    reviewCount: 678,
    inStock: true,
    features: ["Clumping Formula", "Odor Control", "Dust Free", "Easy Cleanup"],
  },
  {
    id: "78",
    name: "Pet Bed",
    description: "Comfortable pet bed with washable cover and orthopedic support.",
    price: 3999,
    image: "/pet-bed-washable-orthopedic.jpg",
    category: "Pets",
    rating: 4.6,
    reviewCount: 456,
    inStock: true,
    features: ["Orthopedic Support", "Washable Cover", "Comfortable", "Durable"],
  },
  {
    id: "79",
    name: "Dog Leash",
    description: "Retractable dog leash with comfortable grip and 16-foot extension.",
    price: 1499,
    image: "/dog-leash-retractable-16-feet.jpg",
    category: "Pets",
    rating: 4.4,
    reviewCount: 789,
    inStock: true,
    features: ["Retractable", "16-Foot Extension", "Comfortable Grip", "Durable"],
  },
  {
    id: "80",
    name: "Pet Toys Set",
    description: "Set of 5 interactive pet toys for dogs and cats with different textures.",
    price: 1999,
    image: "/pet-toys-set-interactive-5-pieces.jpg",
    category: "Pets",
    rating: 4.3,
    reviewCount: 345,
    inStock: true,
    features: ["Set of 5", "Interactive", "Dogs & Cats", "Different Textures"],
  },
  // Kitchen & Dining
  {
    id: "81",
    name: "Non-Stick Pan",
    description: "Premium non-stick frying pan with ceramic coating and heat-resistant handle.",
    price: 2999,
    image: "/non-stick-pan-ceramic-coating.jpg",
    category: "Kitchen",
    rating: 4.6,
    reviewCount: 567,
    inStock: true,
    features: ["Ceramic Coating", "Heat Resistant Handle", "Non-Stick", "Easy Cleanup"],
  },
  {
    id: "82",
    name: "Coffee Maker",
    description: "Programmable coffee maker with 12-cup capacity and auto shut-off feature.",
    price: 7999,
    image: "/coffee-maker-programmable-12-cup.jpg",
    category: "Kitchen",
    rating: 4.5,
    reviewCount: 789,
    inStock: true,
    features: ["12-Cup Capacity", "Programmable", "Auto Shut-Off", "Easy Operation"],
  },
  {
    id: "83",
    name: "Knife Set",
    description: "Professional knife set with 6 knives and wooden block storage.",
    price: 4999,
    image: "/knife-set-professional-6-pieces.jpg",
    category: "Kitchen",
    rating: 4.7,
    reviewCount: 345,
    inStock: true,
    features: ["Professional Grade", "6 Knives", "Wooden Block", "Sharp Blades"],
  },
  {
    id: "84",
    name: "Mixing Bowls",
    description: "Set of 3 stainless steel mixing bowls with non-slip bases.",
    price: 1999,
    image: "/mixing-bowls-stainless-steel-3-pieces.jpg",
    category: "Kitchen",
    rating: 4.4,
    reviewCount: 456,
    inStock: true,
    features: ["Stainless Steel", "Set of 3", "Non-Slip Base", "Dishwasher Safe"],
  },
  {
    id: "85",
    name: "Blender",
    description: "High-speed blender with multiple speed settings and glass jar.",
    price: 5999,
    image: "/blender-high-speed-glass-jar.jpg",
    category: "Kitchen",
    rating: 4.6,
    reviewCount: 678,
    inStock: true,
    features: ["High Speed", "Multiple Settings", "Glass Jar", "Powerful Motor"],
  },
  // Health & Wellness
  {
    id: "86",
    name: "Digital Thermometer",
    description: "Fast-reading digital thermometer with fever alarm and memory function.",
    price: 899,
    image: "/digital-thermometer-fast-reading.jpg",
    category: "Health",
    rating: 4.5,
    reviewCount: 234,
    inStock: true,
    features: ["Fast Reading", "Fever Alarm", "Memory Function", "Accurate"],
  },
  {
    id: "87",
    name: "Blood Pressure Monitor",
    description: "Automatic blood pressure monitor with large display and memory storage.",
    price: 3999,
    image: "/blood-pressure-monitor-automatic-large-display.jpg",
    category: "Health",
    rating: 4.6,
    reviewCount: 456,
    inStock: true,
    features: ["Automatic", "Large Display", "Memory Storage", "Accurate Readings"],
  },
  {
    id: "88",
    name: "Vitamin C Tablets",
    description: "High-potency vitamin C tablets for immune system support.",
    price: 1299,
    image: "/vitamin-c-tablets-high-potency.jpg",
    category: "Health",
    rating: 4.4,
    reviewCount: 789,
    inStock: true,
    features: ["High Potency", "Immune Support", "Easy to Swallow", "Daily Supplement"],
  },
  {
    id: "89",
    name: "First Aid Kit",
    description: "Complete first aid kit with bandages, antiseptic, and medical supplies.",
    price: 1999,
    image: "/first-aid-kit-complete-bandages.jpg",
    category: "Health",
    rating: 4.7,
    reviewCount: 345,
    inStock: true,
    features: ["Complete Kit", "Bandages Included", "Antiseptic", "Emergency Ready"],
  },
  {
    id: "90",
    name: "Hand Sanitizer",
    description: "Alcohol-based hand sanitizer with moisturizing formula and pump dispenser.",
    price: 599,
    image: "/hand-sanitizer-alcohol-based-pump.jpg",
    category: "Health",
    rating: 4.3,
    reviewCount: 567,
    inStock: true,
    features: ["Alcohol Based", "Moisturizing", "Pump Dispenser", "Kills 99.9% Germs"],
  },
  // Travel & Luggage
  {
    id: "91",
    name: "Travel Backpack",
    description: "Durable travel backpack with multiple compartments and laptop sleeve.",
    price: 4999,
    image: "/travel-backpack-durable-laptop-sleeve.jpg",
    category: "Travel",
    rating: 4.6,
    reviewCount: 678,
    inStock: true,
    features: ["Multiple Compartments", "Laptop Sleeve", "Durable", "Travel Ready"],
  },
  {
    id: "92",
    name: "Luggage Set",
    description: "3-piece luggage set with hard shell and 360-degree spinner wheels.",
    price: 12999,
    image: "/luggage-set-3-piece-hard-shell.jpg",
    category: "Travel",
    rating: 4.5,
    reviewCount: 234,
    inStock: true,
    features: ["3-Piece Set", "Hard Shell", "Spinner Wheels", "TSA Lock"],
  },
  {
    id: "93",
    name: "Travel Pillow",
    description: "Memory foam travel pillow with neck support and washable cover.",
    price: 1999,
    image: "/travel-pillow-memory-foam-neck-support.jpg",
    category: "Travel",
    rating: 4.4,
    reviewCount: 456,
    inStock: true,
    features: ["Memory Foam", "Neck Support", "Washable Cover", "Compact"],
  },
  {
    id: "94",
    name: "Passport Holder",
    description: "Leather passport holder with RFID blocking and card slots.",
    price: 1499,
    image: "/passport-holder-leather-rfid.jpg",
    category: "Travel",
    rating: 4.5,
    reviewCount: 345,
    inStock: true,
    features: ["Leather Construction", "RFID Blocking", "Card Slots", "Travel Essential"],
  },
  {
    id: "95",
    name: "Travel Adapter",
    description: "Universal travel adapter with USB ports for worldwide compatibility.",
    price: 2499,
    image: "/travel-adapter-universal-usb.jpg",
    category: "Travel",
    rating: 4.6,
    reviewCount: 567,
    inStock: true,
    features: ["Universal Compatibility", "USB Ports", "Worldwide Use", "Compact Design"],
  },
  // Musical Instruments
  {
    id: "96",
    name: "Acoustic Guitar",
    description: "Full-size acoustic guitar with steel strings and natural wood finish.",
    price: 12999,
    image: "/acoustic-guitar-full-size-steel-strings.jpg",
    category: "Music",
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    features: ["Full Size", "Steel Strings", "Natural Wood", "Rich Sound"],
  },
  {
    id: "97",
    name: "Keyboard",
    description: "61-key electronic keyboard with built-in rhythms and learning modes.",
    price: 8999,
    image: "/keyboard-electronic-61-key.jpg",
    category: "Music",
    rating: 4.5,
    reviewCount: 345,
    inStock: true,
    features: ["61 Keys", "Built-in Rhythms", "Learning Modes", "Portable"],
  },
  {
    id: "98",
    name: "Harmonica",
    description: "Professional harmonica in key of C with reed plates and carrying case.",
    price: 2999,
    image: "/harmonica-professional-key-c.jpg",
    category: "Music",
    rating: 4.4,
    reviewCount: 156,
    inStock: true,
    features: ["Key of C", "Reed Plates", "Carrying Case", "Professional Grade"],
  },
  {
    id: "99",
    name: "Drum Sticks",
    description: "Pair of wooden drum sticks with comfortable grip and balanced weight.",
    price: 899,
    image: "/drum-sticks-wooden-pair.jpg",
    category: "Music",
    rating: 4.3,
    reviewCount: 234,
    inStock: true,
    features: ["Wooden Construction", "Comfortable Grip", "Balanced Weight", "Durable"],
  },
  {
    id: "100",
    name: "Music Stand",
    description: "Adjustable music stand with sheet music holder and portable design.",
    price: 2499,
    image: "/music-stand-adjustable-sheet-holder.jpg",
    category: "Music",
    rating: 4.5,
    reviewCount: 345,
    inStock: true,
    features: ["Adjustable Height", "Sheet Music Holder", "Portable", "Stable Base"],
  },
]

export const categories = [
  "All",
  "Electronics",
  "Clothing",
  "Home & Office",
  "Food & Beverage",
  "Books",
  "Sports",
  "Beauty",
  "Toys",
  "Garden",
  "Automotive",
  "Pets",
  "Kitchen",
  "Health",
  "Travel",
  "Music",
]
